drop table GUESTBOOK;
drop sequence GUESTBOOK_SEQ;

CREATE TABLE GUESTBOOK
(
   NO         NUMBER (20),
   NAME       VARCHAR2 (20),
   PASSWORD   VARCHAR2 (50),
   MESSAGE    VARCHAR2 (2000),
   REG_DATE   DATE
);

ALTER TABLE GUESTBOOK
ADD ( CONSTRAINT guestbook_no_pk PRIMARY KEY ( no ) );

CREATE SEQUENCE GUESTBOOK_SEQ
 START WITH     1
 INCREMENT BY   1
 MAXVALUE       99999999
 NOCACHE
 NOCYCLE;
 
 commit;